# Site settings
title: ShadowWalker's Blog
email: shdowwalker1117@hotmail.com
description: "ShadowWalker‘s blog on github."
baseurl: "/blog"
cdnurl: "http://shadowcdn.qiniudn.com/blog"
url: "http://shadowwalker.github.io/blog"
twitter_username:
github_username: shadowwalker
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 7
exclude: ["node_modules"]
