# Site settings
title: ShadowWalker's Blog
email: shdowwalker1117@hotmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "http://shadowwalker.github.io/blog"
twitter_username:
github_username:  shadowwalker
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 7
exclude: ["node_modules"]
